
apiVersion: v1
kind: Secret
metadata:
  name: db-config
  namespace: default
type: Opaque
data:
  POSTGRES_USER: postgres
  POSTGRES_PASSWORD: postgres

--- 

apiVersion: apps/v1
kind: Deployment
metadata:
  name: db
  namespace: default
  labels:
    app : db
spec:
  selector:
    matchLabels:
      app: db
  replicas: 1
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app:  db
    spec:
      containers:
      - name:  db
        image:  postgres:15-alpine
        resources:
          requests:
            cpu: 100m
            memory: 100Mi
          limits:
            cpu: 100m
            memory: 100Mi
        envFrom :
        - secretRef:
            name: db-config
        ports:
        - containerPort:  5432
          name:  postgres
        volumeMounts:
        - name: db-data
          mountPath: /var/lib/postgresql/data
      volumes:
        - name: db-data
          emptyDir : {}
      restartPolicy: Always

--- 
apiVersion: v1
kind: Service
metadata:
  name: db
  namespace: default
  labels:
    app : db
spec:
  selector:
    app: db
  type: ClusterIP
  ports:
  - name: db
    protocol: TCP
    port: 5432
    targetPort: 5432 
